FROM golang:1.20 AS preloader
LABEL stage=intermediate-build
WORKDIR /exec
COPY ./go.* ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 go build -o bin/preload
CMD ["./bin/preload"]

FROM mysql:latest AS mysql-db

RUN chown -R mysql:root /var/lib/mysql/
ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD
ARG DATABASE_ANALYTICS
ARG ANALYTICS_UPSTREAM

ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ENV DATABASE_ANALYTICS=$DATABASE_ANALYTICS
ENV ANALYTICS_UPSTREAM=${ANALYTICS_UPSTREAM}

ADD ./data/data.sql /etc/mysql/data.sql
RUN sed -i 's/MYSQL_DATABASE/'$MYSQL_DATABASE'/g' /etc/mysql/data.sql
RUN cp /etc/mysql/data.sql /docker-entrypoint-initdb.d

EXPOSE 3306
